groups:
  - name: reviewers # name of the group
    reviewers: 2 # how many reviewers do you want to assign?
    internal_reviewers: 2 # how many reviewers do you want to assign when the PR author belongs to this group?
    usernames: # github usernames of the reviewers
      - Seayay
      - Big-Cake-jpg
      - bingxin666
      - XieXiLin2