name: "提交崩溃"
description: 上传未收录的崩溃类型
title: "📄[UPLOAD-CRASH] 请输入标题"
labels: [
  "崩溃提交"
]
body:
  - type: checkboxes
    id: check-list
    attributes:
      label: "检查项"
      description: "请逐个检查下列项目，并勾选确认。"
      options:
        - label: "我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组"
          required: true
        - label: "我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法"
          required: true
  - type: textarea
    id: description
    attributes:
      label: "描述问题"
      description: 请简单描述您遇到的问题
      placeholder: 问题描述……
      render: bash
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "您正在进行的操作是？"
      description: 请详细描述崩溃发生时你正在做的事
      value: |
        1. 
        2. 
        3. 
        4. 游戏崩溃
      render: bash
    validations:
      required: true
  - type: textarea
    id: log-files
    attributes:
      label: "日志文件"
      description: 请优先使用 [MCLogs](https://mclo.gs) 提交日志
      placeholder: 粘贴 MCLogs 链接、粘贴日志内容或上传日志文件
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "操作系统"
      description: 您使用的操作系统是？
      multiple: false
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: true
  - type: dropdown
    id: dropdown
    attributes:
      label: "客户端 / 服务端"
      description: 出现崩溃的位置是客户端 / 服务端？
      multiple: false
      options:
        - 客户端
        - 服务端
    validations:
      required: true
